# Logging and Output arguments
log_level: info
logging_strategy: steps
logging_steps: 1
report_to:
- wandb
- tensorboard
save_strategy: steps
save_steps: 1000
output_dir: data/Doge-100M
overwrite_output_dir: true
push_to_hub: true
private: true
token: <your-token>
hub_model_id: Doge-100M
hub_strategy: every_save

# Model arguments
model_init_kwargs:
  vocab_size: 128256
  hidden_size: 512
  intermediate_size: 1536
  num_hidden_layers: 16
  hidden_dropout: 0.0
  hidden_act: "silu"
  tie_word_embeddings: True
  keep_window_size: 2048
  max_position_embeddings: 2048
  rope_theta: 10000.0
  num_attention_heads: 4
  num_key_value_heads: 2
  bos_token_id: 128000
  eos_token_id: 128001
  pad_token_id: 128001
  attn_implementation: sdpa
  torch_dtype: bfloat16

model_name_or_path: SmallDoge/Doge-tokenizer
model_revision: main
trust_remote_code: true

# Dataset arguments
datasets_and_ratios:
  - "<dataset_name_or_path>": 1.0
total_sample_size: 8000000
dataset_text_field: "text"
max_length: 2048
packing: false
dataset_num_proc: 4
cache_dir: "./cache"

# PT trainer arguments
preprocessing_num_workers: 1 # Equal to the number of GPUs you are using
seed: 233
do_train: True
max_steps: 12800
per_device_train_batch_size: 1
do_eval: False
eval_strategy: 'no'
eval_steps: 100
per_device_eval_batch_size: 1
optim: adamw_torch_fused
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-8
learning_rate: 6.0e-3
lr_scheduler_type: warmup_stable_decay
lr_scheduler_kwargs:
  warmup_type: linear
  decay_type: linear
  num_decay_steps: 2560
  min_lr_ratio: 0.0
warmup_steps: 2000
weight_decay: 0.01
gradient_accumulation_steps: 512
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
max_grad_norm: 1.0
bf16: True
